manala:
    description: Wamiz - Symfony application using a Docker-hybrid stack
    template: .manala.yaml.tmpl
    sync:
        - .manala/
        - docker-compose.yaml.tmpl
        - php.ini.tmpl

system:
    # @option {"label": "App name (in kebab-case)"}
    # @schema {"type": "string"}
    app_name: ~
    # @schema {"type": ["string"], "pattern": "^[a-zA-Z]+/[a-zA-Z]+$"}
    timezone: Etc/UTC
    php:
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "config": {"type": ["object", "string", "array"]}
        #         }
        #     }
        # }
        configs: []
    mariadb:
        # @option {"label": "MariaDB version"}
        # @schema {"enum": [null, 10.3, 10.4, 10.5, 10.6]}
        version: ~
        # @schema {"type": ["string", "null"]}
        init: ~
        # @option {"label": "MariaDB ports"}
        # @schema {"type": ["array"]}
        ports: ~
    redis:
        # @option {"label": "Redis version"}
        # @schema {"enum": [null, "*"]}
        version: ~
        # @option {"label": "Redis ports"}
        # @schema {"type": ["array"]}
        ports: ~
    mailcatcher:
        # @option {"label": "Mailcatcher version"}
        # @schema {"enum": [null, "*"]}
        version: ~
        # @option {"label": "Mailcatcher ports"}
        # @schema {"type": ["array"]}
        ports: ~
    phpmyadmin:
        # @option {"label": "PhpMyAdmin ports"}
        # @schema {"type": ["array"]}
        ports: ~
    phpredisadmin:
        # @option {"label": "PhpRedisAdmin ports"}
        # @schema {"type": ["array"]}
        ports: ~
